### ISSUE TITLE
Using a soft link to the pdf document

### ISSUE THREAD

**Issue by jorgechp** [lulivi/Latex-PDF-auto-updater#1]
https://github.com/lulivi/latex-project-example/blob/043abf94e509240648706093fb7fca6474af2f33/src/update_pdf_latex.sh#L108

I think it should be better to make a soft link to the directory instead of calling a listener for "$BUILD_DIR/$OUT_DOC_NAME.pdf"

**Comment by lulivi** [comment]
Good idea but the soft link doesn't update the pdf in the viewer.
